blueprint:
  name: Scheduled Switch Control
  description: Turn on a switch at a specified time on selected days of the week and control the duration.
  domain: automation
  input:
    switch_entity:
      name: Switch Entity
      description: The entity ID of the switch to control.
      selector:
        entity:
          domain: switch
    run_time:
      name: Run Time
      description: The time to turn on the switch.
      selector:
        time: {}
    run_days:
      name: Run Days
      description: Days of the week to run the automation.
      selector:
        type: select
        options:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
        multiple: true
    duration:
      name: Duration
      description: Duration for which the switch stays on.
      default: "00:15:00"
      selector:
        time: {}
mode: restart
max_exceeded: silent

trigger:
  - platform: time
    at: !input run_time

condition:
  - condition: time
    weekday: !input run_days

action:
  - service: switch.turn_on
    target:
      entity_id: !input switch_entity
  - delay: !input duration
  - service: switch.turn_off
    target:
      entity_id: !input switch_entity
